- src/lib.rs
- src/parser/mod.rs
This PR adds the use of nom's `all_consuming` parser to the top level path parser, to ensure that any malformed JSONPath segments at the tail end of the query string are not discarded and ignored, leading to unexpected behaviour.
Some of the docs were also updated.
> Prevent unexpected behaviour from malformed trailing query string

- CHANGELOG.md
- src/lib.rs
- tests/spec_examples.rs
This PR extends the `NodeList` type's API to include two new methods: `NodeList::exactly_one` and `NodeList::at_most_one`.
Consider the following `Value`:
```rust
let value = json!({"foo": ["bar", "baz"]});
```
The `at_most_one` method is meant to replace the original `one` method. It works similarly, however, is fallible in the case where more than one node is produced by the query:
```rust
let path = JsonPath::parse("$.foo[10]")?;
let node = path.query(&value).at_most_one().unwrap();
assert_eq!(node, None);
```
```rust
let path = JsonPath::parse("$.foo[0]")?;
let node = path.query(&value).at_most_one().unwrap();
assert_eq!(node, Some(&json!("bar")));
```
```rust
let path = JsonPath::parse("$.foo.*")?;
let error = path.query(&value).at_most_one().unwrap_err();
assert!(matches!(error, …
```
> [11] `NodeList` API Improvements

- CHANGELOG.md
- src/node.rs
This adds the `get`, `first`, and `last` methods to the `NodeList` type.
In addition, the function signature of the `at_most_one` and `exactly_one` methods were altered to take `&self` instead of `self`, as they did not need to take ownership.
> Further enhancements to `NodeList`

- src/parser/primitive/string.rs
This PR fixes the new clippy lints introduced in 1.68.0, and that were caught by the new CI action.
> Fix new clippy lints for 1.68.0

- src/error.rs
- src/node.rs
- src/path.rs
This PR adds tests to ensure that the `JsonPath` and `NodeList` remain `Send` and `Sync`.
> Add tests to ensure Send and Sync on public API

- CHANGELOG.md
- src/lib.rs
This PR updates some of the crate level documentation to more accurately reflect recent changes, and improve some of the wording.
A bad link to the integration tests was also fixed.
> Fix a link in the docs, and update wording

- CHANGELOG.md
- src/parser/mod.rs
- src/parser/segment.rs
- src/parser/selector/filter.rs
- src/parser/selector/mod.rs
- src/parser/selector/slice.rs
- src/path.rs
The Clone trait was implemented for the `JsonPath` type, by deriving it on all of its nested types.
This is related to #23 .
> [23] Implement `Clone` for `JsonPath`

- CHANGELOG.md
- src/parser/mod.rs
- src/path.rs
This PR implements `Default` for the `JsonPath` type. It defaults to a root JSONPath query, i.e., `$`.
This is addressing, in part, #23
> [#23] Implement `Default` for `JsonPath`

- CHANGELOG.md
- src/parser/mod.rs
- src/parser/segment.rs
- src/parser/selector/filter.rs
- src/parser/selector/mod.rs
- src/parser/selector/slice.rs
- src/path.rs
This implements the Display and Serialize traits for the JsonPath type. Although there may be a more efficient way to serialize it than using collect_str, my assumption for now is that JSON Path query strings are not too long and this will not be too costly to rely on the Display impl to allocate a string before writing out to the serializer.
Related to #23
> [#23] Implement `Display` and `Serialize` for `JsonPath`

- CHANGELOG.md
- src/node.rs
The NodeList type was changed to be a newtype so that it would serialize as the raw list of nodes.
This closes #29
> [#29] Fix Serialization of `NodeList`

- serde_json_path/CHANGELOG.md
- serde_json_path/src/path.rs
- serde_json_path_core/src/spec/functions.rs
- serde_json_path_core/src/spec/query.rs
- serde_json_path_core/src/spec/segment.rs
- serde_json_path_core/src/spec/selector/filter.rs
- serde_json_path_core/src/spec/selector/index.rs
- serde_json_path_core/src/spec/selector/mod.rs
- serde_json_path_core/src/spec/selector/name.rs
- serde_json_path_core/src/spec/selector/slice.rs
This will close #23 as I do not see any value in implementing `Hash`, `Ord`, or `PartialOrd` for now.
> [#23] Implement Eq for JsonPath and nested types

- serde_json_path/CHANGELOG.md
- serde_json_path/src/error.rs
- serde_json_path/src/ext.rs
- serde_json_path/src/lib.rs
- serde_json_path/src/parser/mod.rs
- serde_json_path/src/path.rs
- serde_json_path_core/src/node.rs
The Error type was renamed to ParseError to reflect the fact that it is only used for parsing errors.
This is not related to any issues.
> Rename `Error` to `ParseError`

- serde_json_path/Cargo.toml
- serde_json_path_core/Cargo.toml
- serde_json_path_macros/Cargo.toml
* The version was removed from the `serde_json_path_core` crate's dev-dependency of `serde_json_path` to allow for publishing to crates.io
* `serde_json_path` was removed as a dev-dependency from `serde_json_path_macros` as it was not used
> Fix `Cargo.toml` files for publishing

- serde_json_path/Cargo.toml
The `env_logger` dev-dependency was not being used by `serde_json_path` so it was removed.
> Remove `env_logger` from `serde_json_path`

- serde_json_path/CHANGELOG.md
- serde_json_path/README.md
- serde_json_path/src/lib.rs
This closes #40 by updating any links to the JSONPath specification document to the latest version (base 14).
> Update JSONPath Specification Links

- serde_json_path/CHANGELOG.md
- serde_json_path/src/parser/segment.rs
- serde_json_path/src/parser/selector/filter.rs
- serde_json_path/src/parser/selector/function/mod.rs
- serde_json_path/tests/compliance.rs
The CTS was updated to include the latest tests that have been added since last update. This caused some breakages, which required changes to be fixed.
In general, the usage of `space0` nom parser was replaced with `multispace0` in order to support new lines in query strings.
This closes #42 .
> [#42] Update CTS and make necessary fixes

- RELEASE-CHECKLIST.md
I felt it necessary to create a release checklist after having just gone through the release process for the first time in a couple of months.
> Add a Release Checklist

- RELEASE-CHECKLIST.md
One critical step was missing from my release checklist: tagging the release in Github. This PR adds that item to the list, and along with actually tagging the most recent release, closes #47
> Add a line for tagging the release to the release checklist

- serde_json_path/CHANGELOG.md
- serde_json_path/tests/regressions.rs
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/src/spec/selector/filter.rs
This should close #49 - in which false positive query results were being produced by filters using relative singular query strings as comparables.
In addition to fixing the bug, some additional tracing instrumentation was added to lower level query evaluation functions.
> [#49] Fix bug producing false positives in filters

- serde_json_path/CHANGELOG.md
- serde_json_path/src/lib.rs
- serde_json_path/src/parser/mod.rs
- serde_json_path/src/parser/primitive/string.rs
This is part of #41
The Descendant Operator (`..`) section has had a line added briefly describing it and linking to the relevant definition in the JSONPath spec.
> [#41] Add a line briefly describing descendant operator in docs

- serde_json_path/CHANGELOG.md
- serde_json_path/src/lib.rs
This relates to #41 
An example that makes clearer usage of absolute paths via `$` in filters is provided.
> [#41] Add a better example to the Filter section in main docs

- serde_json_path/CHANGELOG.md
- serde_json_path/src/parser/selector/function/registry.rs
- serde_json_path/tests/regressions.rs
This PR closes #60. Parentheses were added to the formulated regex used by the `match` function to ensure full input string was being matched. A regression test was added to check for correct behaviour.
> [#60] Fix the `match` function to properly match full string

- serde_json_path/CHANGELOG.md
- serde_json_path/Cargo.toml
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/Cargo.toml
> Release 0.6.3

- serde_json_path/Cargo.toml
The version number was not bumped in the `Cargo.toml` file.
> Release 0.6.3 (round 2)

- serde_json_path/CHANGELOG.md
- serde_json_path/src/parser/primitive/number.rs
- serde_json_path/src/parser/segment.rs
- serde_json_path/tests/compliance.rs
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/src/spec/selector/filter.rs
This PR updates the Compliance Test Suite (CTS) to its latest state in the sub-repository, and provides fixes for two new tests that were failing.
There was no issue for this PR.
> Compliance Update

- serde_json_path/CHANGELOG.md
- serde_json_path/src/lib.rs
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/src/lib.rs
- serde_json_path_core/src/spec/segment.rs
- serde_json_path_macros/CHANGELOG.md
- serde_json_path_macros/src/lib.rs
The `private_in_public` lint that was deprecated has been removed by this PR.
The `descend` method used to query descendent operators had its tracing instrumentation named properly.
> Fix new lints in Rust 1.74

- serde_json_path/CHANGELOG.md
- serde_json_path/src/parser/primitive/int.rs
- serde_json_path/src/parser/segment.rs
- serde_json_path/src/parser/selector/filter.rs
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/src/spec/selector/slice.rs
- serde_json_path_macros/CHANGELOG.md
- serde_json_path_macros/src/internal/common/extract.rs
This closes #69.
`TODO`s from the linked issue were addressed, with the exception of the one in macros to emit warnings when invalid arguments are encountered during expansion.
> [#69] Remove `TODO`s from code

- serde_json_path/CHANGELOG.md
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/src/node.rs
> Fix `clippy` lints for Rust 1.75

- LICENSE-MIT
- serde_json_path/CHANGELOG.md
- serde_json_path/README.md
- serde_json_path/src/lib.rs
- serde_json_path/src/path.rs
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/src/path.rs
- serde_json_path_core/src/spec/functions.rs
This PR updates links to refer to the new JSONPath standard ([RFC 9535](https://www.rfc-editor.org/rfc/rfc9535.html))
> docs: refer to RFC 9535

- serde_json_path/CHANGELOG.md
- serde_json_path/Cargo.toml
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/Cargo.toml
- serde_json_path_macros/CHANGELOG.md
- serde_json_path_macros/Cargo.toml
> Release `0.6.6`

- serde_json_path/CHANGELOG.md
- serde_json_path/src/parser/selector/function/registry.rs
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/src/spec/functions.rs
- serde_json_path_macros/CHANGELOG.md
Closes #83 
This fixes an issue that was preventing registered functions from being used as arguments to other functions.
> fix: bug found with new CTS

- serde_json_path/CHANGELOG.md
- serde_json_path/tests/compliance.rs
- serde_json_path_core/CHANGELOG.md
- serde_json_path_macros/CHANGELOG.md
This PR updates to the latest CTS, which now contains tests for non-detreministic behaviour. The `compliance` integration test was updated to support this, and the new non-deterministic tests added to the CTS are now ✅.
> test: handle non-determinism tests

- .github/workflows/ci.yml
- deny.toml
- serde_json_path/CHANGELOG.md
- serde_json_path/Cargo.toml
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/Cargo.toml
- serde_json_path_macros/CHANGELOG.md
- serde_json_path_macros/Cargo.toml
This PR releases 0.6.7, and also initializes `cargo deny` to check for licenses and audit warnings etc., although, it does not add it to CI
> Release 0.6.7

- .github/workflows/cts.yml
This PR adds a workflow to run a nightly job that updates submodules and runs tests, to check if `serde_json_path` is passing the compliance test suite (CTS).
> feat: add nightly submodule update and check

- serde_json_path/CHANGELOG.md
- serde_json_path/src/parser/selector/function/registry.rs
Update after latest CTS surfaced an edge case for i-regexp compliance.
Use [CRLF mode](https://docs.rs/regex/latest/regex/#grouping-and-flags) in regexes for search and match functions so that the line feed and new line characters are treated properly with a dot matcher
Closes #90
> fix: use CRLF mode in regexes for match and search

- serde_json_path/CHANGELOG.md
- serde_json_path/Cargo.toml
- serde_json_path/src/lib.rs
- serde_json_path/src/parser/selector/function/registry.rs
First off, love this library, thanks for it. For my use case I don't really need the regex functions, and it's a really large dependency to pull in (adds ~8s to my build process).
This change hides the regex functions (`match` and `search`) behind a feature flag `regex`, which is enabled by default. This allows consumers to completely eliminate regex as a dependency if they choose. Also added some docs on feature flags.
I wasn't sure if I should update the changelog since it looks like it might be auto-generated from git cliff, let me know what you'd like.
> feat: Add `regex` feature flag

- .github/workflows/ci.yml
- .github/workflows/cts.yml
- deny.toml
`checkout@v3` is outdated and currently shows the following warning for your workflow runs:
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
There is also a new version for cargo-deny-action: [v2.0.0](https://github.com/EmbarkStudios/cargo-deny-action/releases/tag/v2.0.0)
Should I update that as well? And update `deny.toml` to match the [current template](https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml)?
As side note: You can [configure Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dep …
> Update GitHub workflow actions

- .github/dependabot.yml
As discussed in https://github.com/hiltontj/serde_json_path/pull/94#issuecomment-2266471331
You can also enable Dependabot for the Rust dependencies (but I haven't done that before with Cargo Workspaces). And you can also customize Dependabot in multiple ways, such as grouping update pull requests, ignoring certain dependencies, ignoring patch version updates, ...
> Enable Dependabot for GitHub actions

- .github/dependabot.yml
> chore: add dependabot for Rust

- serde_json_path/CHANGELOG.md
- serde_json_path/src/parser/primitive/int.rs
- serde_json_path/src/parser/segment.rs
- serde_json_path/src/parser/selector/mod.rs
- serde_json_path/src/parser/selector/slice.rs
- serde_json_path_core/CHANGELOG.md
- serde_json_path_core/src/spec/integer.rs
- serde_json_path_core/src/spec/mod.rs
- serde_json_path_core/src/spec/selector/index.rs
- serde_json_path_core/src/spec/selector/slice.rs
This PR is to address [the recent CTS failure](https://github.com/hiltontj/serde_json_path/actions/runs/10232236116).
The JSONPath spec states that integers, e.g., those used as indices or in slice selectors, must be within a specific range [-2^53 +1, 2^53 - 1] (see [here](https://www.rfc-editor.org/rfc/rfc9535.html#section-2.1-4.1)).
The CTS recently added tests to verify this behaviour in https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/90, and `serde_json_path` which was not accounting for it, was failing the updated CTS.
This PR adds a new `Integer` type to represent such integers and check that they stay within that range. It also caught a couple of places where overflows would have led to panics.
> feat: implement integer type to comply with spec

- serde_json_path_core/src/spec/integer.rs
- serde_json_path_core/src/spec/selector/index.rs
- serde_json_path_core/src/spec/selector/slice.rs
> refactor: updates to Integer API

- deny.toml
- serde_json_path/src/path.rs
- serde_json_path_core/src/node.rs
- serde_json_path_core/src/path.rs
- serde_json_path_core/src/spec/functions.rs
No issue for this. This fixes clippy lints from 1.83.0. Yay elided lifetimes.
> chore: fix clippy lints from 1.83.0

- serde_json_path_core/src/path.rs
The RFC defines how to [format normalized path names]. Notably, it defines the escape character as `ESC normal-escapable`, but doesn't define `ESC` in that section. It is, however, defined for [name selector syntax] as `%x5C; \ backslash`. I'm therefore reasonably sure that the current behavior of serde_json_path when formatting normalized paths is incorrect, as it results in no escaping of `'` at all.
For example, using [the sandbox] to select `$.*` from `{"O'Reilly": true}` returns
```json
[
{
"loc": "$['O'Reilly']",
"node": true
}
]
```
I worked this out while building the location feature into [Go jsonpath] (many thanks for the inspiration in your crate!). This [playground link] shows what I believe to be the correct escaping (doubled for inclusion in JSON):
``` json
[
{
"node": true, …
```
> Properly format normalized path names
