hiltontj/serde_json_path

.gitmodules
src/parser/primitive/string.rs
src/parser/selector/filter.rs
tests/compliance.rs

This PR brings in the JSONPath Compliace Test Suite (CTS) as an integration test.
The CTS highlighted some major flaws in the string literal parsing logic, which were fixed to match the JSONPath specification.

Incorporate JSONPath Compliance Test Suite

---

.gitmodules
src/parser/primitive/string.rs
src/parser/selector/filter.rs
tests/compliance.rs

This PR updates the compliance test suite sub-repo to point at the correct one. Previously, it was pointing at a fork of the correct one, by mistake.
The correct test suite had more test cases, and so this PR makes some fixes to address bugs found through those test cases.

[5] Update CTS sub-repo and fix as many tests as possible

---

CHANGELOG.md
Cargo.toml

Release `0.5.0`

---

CHANGELOG.md
Cargo.toml

Release 0.5.1

---

CHANGELOG.md
Cargo.toml

Release 0.5.2

---

CHANGELOG.md
Cargo.toml

Release 0.5.3

---

serde_json_path/CHANGELOG.md

[#5] Update the CTS to latest

---

CHANGELOG.md
serde_json_path/README.md

* Update some links in README
* Remove the Planned Development section in README
* Add a CHANGELOG file to root that points at the `serde_json_path` crate CHANGELOG file

Add root changelog and make some readme updates

---

serde_json_path/CHANGELOG.md
serde_json_path/Cargo.toml
serde_json_path/README.md
serde_json_path_core/Cargo.toml
serde_json_path_macros/Cargo.toml

Release 0.6.0

---

serde_json_path/CHANGELOG.md
serde_json_path/Cargo.toml

This PR releases version 0.6.1. See the change log for details of what changed.

Release 0.6.1

---

serde_json_path/CHANGELOG.md
serde_json_path/Cargo.toml
serde_json_path_core/CHANGELOG.md
serde_json_path_core/Cargo.toml

Release 0.6.2

---

serde_json_path/CHANGELOG.md
serde_json_path/src/lib.rs

This relates to #41
This PR improves the examples in the documentation for using the slice selector.

improve slice selector examples in docs

---

Cargo.toml
serde_json_path/CHANGELOG.md
serde_json_path/README.md
serde_json_path/src/lib.rs
serde_json_path_core/src/node.rs

This PR is meant to cover several documentation improvements from #41.

[#41] Documentation Improvements

---

serde_json_path/CHANGELOG.md

Fixed a broken link in the changelog

Quick Changelog fix

---

serde_json_path/CHANGELOG.md
serde_json_path_core/CHANGELOG.md
serde_json_path_core/src/node.rs

[#64] Add methods to `ExactlyOneError`

---

serde_json_path/CHANGELOG.md
serde_json_path/Cargo.toml
serde_json_path_core/CHANGELOG.md
serde_json_path_core/Cargo.toml
serde_json_path_macros/CHANGELOG.md
serde_json_path_macros/Cargo.toml
serde_json_path_macros/src/internal/Cargo.toml

This PR is for releasing `v0.6.5`.

Release: `0.6.5`

---

.github/workflows/cts.yml
serde_json_path/README.md

This PR adds a badge to show compliance status, based on the nightly CTS test run.

docs: add compliance badge to README

---

serde_json_path/CHANGELOG.md
serde_json_path/src/parser/selector/filter.rs
serde_json_path/tests/functions.rs

fix: better error message for incorrect function return type

---

serde_json_path/CHANGELOG.md

chore: update changelog

---

Cargo.toml
serde_json_path/Cargo.toml
serde_json_path_core/Cargo.toml
serde_json_path_macros/Cargo.toml
serde_json_path_macros/src/internal/Cargo.toml

Updated the `Cargo.toml` files to make use of workspace dependencies.

chore: workspace consolidation
